### ISSUE TITLE
FR: Allow setting for branch name

### ISSUE THREAD

**Issue by peirix** [undergroundwires/bump-everywhere#14]
Right now it expects the main branch to be named `master`, but ours is `main`, so the build fails. It would be nice to have that setting alongside `repository` and `user`

**Comment by undergroundwires** [comment]
Hi, thanks! It makes sense. I improve some other aspects, once it's done I'll release next minor version with this feature with two changes:

1. No more hardcoded 'master'. Default configuration will check the default branch of the origin and find out the main branch. If origin does not exist (which is a very rare use-case); it will consider `master` is the main branch if it exists, or `main` if that exists. If none exists, it will exit with an error. This would allow better zero-config start.

2. An argument like `--branch` that would override the logic from 1. What you're looking for 😀

**Comment by undergroundwires** [comment]
I just realized that I was overthinking this with point 1. Just running `git push` without specifying any branch (removing hardcoded `master`) was enough to point to default branch 😀 `--branch` is also introduces now. Changes are released as [`1.4.0`](https://github.com/undergroundwires/bump-everywhere/releases/tag/1.4.0).

**Comment by undergroundwires** [comment]
I just realized that I was overthinking this with point 1. Just running `git push` without specifying any branch (removing hardcoded `master`) was enough to point to default branch 😀 `--branch` option is also introduced now, but should not be necessary. Changes are released as [`1.4.0`](https://github.com/undergroundwires/bump-everywhere/releases/tag/1.4.0) and published to marketplace.
