### ISSUE TITLE
validate version in package.json

### ISSUE THREAD

**Issue by espensgr** [undergroundwires/bump-everywhere#2]
I made a release with version number 2.21 and when that version is added to the package.json i get an error in my build:
npm ERR! Invalid version: "2.21"

Maybe add [node semver](https://github.com/npm/node-semver) to the job to verify right format, from the npm documentation: https://docs.npmjs.com/files/package.json#version

**Comment by undergroundwires** [comment]
Hi @espensgr , thanks for the feedback 👍. You're right the version should be validated before any update.

Node is a very big dependency that I do not want to introduce. Right know the OS + code is only [![Docker image size](https://img.shields.io/docker/image-size/undergroundwires/bump-everywhere)](https://hub.docker.com/r/undergroundwires/bump-everywhere) 😊

However `node-samver` is very good reference implementation, the [validation logic](https://github.com/npm/node-semver/blob/60880700d6cee8450e37f5ac31430d84587620f5/classes/semver.js#L25) from `samver.js` should be ported using bash/shell script. 

The version string should be validated when:
- [reading last version](https://github.com/undergroundwires/bump-everywhere/blob/ab66bf763fa3823dc07588a512760e85027680f2/scripts/bump-and-tag-version.sh#L55)
- [increasing the version](https://github.com/undergroundwires/bump-everywhere/blob/ab66bf763fa3823dc07588a512760e85027680f2/scripts/bump-and-tag-version.sh#L74)

It'll then exit with fail error code if latest tag does not conform to samver standards.

Thank you again. I'll take a look at the implementation when I have time this week.

**Comment by undergroundwires** [comment]
I added validation with #4, and the behavior is like this now:

Tag latest commit with invalid semantic version string e.g. `2.1.` and now the action fails with following:
 
```
2020-07-07T16:12:30.8005615Z Setting up credentials
2020-07-07T16:12:30.8066911Z Bumping and tagging version
2020-07-07T16:12:30.8154334Z Version "2.1" is invalid (not in `major.minor.patch` format)
2020-07-07T16:12:30.8172484Z Latest commit tag "2.1" in commit "13423ec5feece2445edcbb87f45f0982bf52b227" is not a version string
```

**Comment by undergroundwires** [comment]
The validation logic is published in [latest version](https://github.com/undergroundwires/bump-everywhere/releases/tag/1.0.2)

**Comment by undergroundwires** [comment]
The validation logic is published in [latest version](https://github.com/undergroundwires/bump-everywhere/releases/tag/1.0.2), thanks again for your contribution @espensgr, hope I understood you correctly.
